version: "3"

services:
  lambda-draw-donuts-chart:
    platform: linux/x86_64 #ベースイメージがx86_64しか提供していないので互換モードでビルドする
    build: .
    container_name: lambda-draw-donuts-chart
    tty: true
    ports:
      - "9000:8080"
    environment:
      AWS_ACCESS_KEY_ID: "dummy"
      AWS_SECRET_ACCESS_KEY: "dummy"
      AWS_SESSION_TOKE: "dummy"
      ENV: "local"
    command: out/handler.main
  localstack:
    image: localstack/localstack-light:0.14
    container_name: localstack
    # containerの起動と終了を繰り替えすような操作をする場合bucketの作成とfileのcopyを毎回面倒なのでdirのmountを行うと永続化される
    # 常に有効にすると意図しないfileがuploadされたままlambdaを実行しても気が付かないのでコメントアウトする
    # volumes:
      # - ./localstack/s3:/tmp/localstack/s3
    ports:
      - "4566:4566"
    environment:
      DEFAULT_REGION: "ap-northeast-1"
      SERVICES: "s3"
      USE_SSL: "true"
      DATA_DIR: "/tmp/localstack/s3"